// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgqloudazjlfqllrsyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ3Fsb3VkYXpqbGZxbGxyc3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MzA4MTEsImV4cCI6MjA2ODIwNjgxMX0.cXNUa5ifKA75E1FX7BnJ50sjDoqEDa78bZeGXBWt5Yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});